### ISSUE TITLE
BackEnd: Optimize queue scheduling to improve machine resource utilization

### ISSUE THREAD

**Issue by EdmondFrank** [oss-compass/compass-service-scheduler#1]
Compass' queue scheduling at this stage is very simple, just parallel preemptive scheduling.

As a result, when multiple pipelines are scheduled concurrently, they often do not block in the same calm point bottleneck, e.g., data collection and or enrich steps.

![Image](https://user-images.githubusercontent.com/13914416/234450487-924b0ecc-f9c2-4fb9-bd39-6522d1a11c96.png)

**Comment by EdmondFrank** [comment]
After through an external scheduler, the tasks in the queue that are being executed in the corresponding phase are controlled.

![Image](https://user-images.githubusercontent.com/13914416/234546603-69c28b94-3fea-4c54-8a92-9ca75b6ebb0b.png)

**Comment by eyehwan** [comment]
Looks Great!

**Comment by EdmondFrank** [comment]
![Image](https://user-images.githubusercontent.com/13914416/234777503-c55529e6-c873-448a-9c32-b1ede7c4f885.png)
