### ISSUE TITLE
Back End: Separate processing of raw/enrich data and model config file generation in the pipeline.(流水线中raw/enrich 与 model config 文件生成分开处理)

### ISSUE THREAD

**Issue by eyehwan** [oss-compass/compass-service-scheduler#5]
流水线中raw/enrich 与 model config 文件生成分开处理

**Comment by EdmondFrank** [comment]
By generalizing and parameterizing the steps of each pipeline, the incompatible changes can be updated by adding the existing steps and the new ones with differences to form a new pipeline. 

For example：



![Image](https://github.com/oss-compass/compass-service-scheduler/assets/13914416/ccef632b-592c-4a02-8b8b-de8b9d0a0a13)


The pipeline above extracts the steps by combining the new lab parameters with the existing routine steps of the metrics model to form a new pipeline of the lab model.
